PARAMETERS:
  BEAM_LENGTH:
    - 3.0
    - 6.0
  BEAM_WIDTH:
    - 0.2
    - 0.4
  BEAM_HEIGHT:
    - 0.4
    - 0.6
  GRID_WIDTH:
    - 9 
    - 18
  GRID_HEIGHT:
    - 6
    - 10
  GRID_DEPTH:
    - 9
    - 18
  YOUNG_MODULUS:
    - 2.5e+10
    - 4.3e+10
  DENSITY:
    - 2.0e+3
    - 2.6e+3
  PRESSURE:
    - 2.0e+3
    - 3.0e+3
  SEED: 1
DIRECTORY: datasets/stand_medium_test
NUM_STRUCTURES: 1000
NUM_PROBLEMS_PER_STRUCTURE: 1
